# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recorder/proto/recorder.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1drecorder/proto/recorder.proto\x12\x16pirateshooter.recorder\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x01\n\x14SendDataPointRequest\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0esteering_angle\x18\x02 \x01(\x02\x12\x13\n\x0bwheel_speed\x18\x03 \x01(\x02\x12\r\n\x05image\x18\x04 \x01(\x0c\"\x17\n\x15SendDataPointResponse2\x7f\n\x0fRecorderService\x12l\n\rSendDataPoint\x12,.pirateshooter.recorder.SendDataPointRequest\x1a-.pirateshooter.recorder.SendDataPointResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recorder.proto.recorder_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENDDATAPOINTREQUEST._serialized_start=91
  _SENDDATAPOINTREQUEST._serialized_end=220
  _SENDDATAPOINTRESPONSE._serialized_start=222
  _SENDDATAPOINTRESPONSE._serialized_end=245
  _RECORDERSERVICE._serialized_start=247
  _RECORDERSERVICE._serialized_end=374
# @@protoc_insertion_point(module_scope)
