# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from recorder.proto import recorder_pb2 as recorder_dot_proto_dot_recorder__pb2


class RecorderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDataPoint = channel.unary_unary(
                '/pirateshooter.recorder.RecorderService/SendDataPoint',
                request_serializer=recorder_dot_proto_dot_recorder__pb2.SendDataPointRequest.SerializeToString,
                response_deserializer=recorder_dot_proto_dot_recorder__pb2.SendDataPointResponse.FromString,
                )


class RecorderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDataPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecorderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDataPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDataPoint,
                    request_deserializer=recorder_dot_proto_dot_recorder__pb2.SendDataPointRequest.FromString,
                    response_serializer=recorder_dot_proto_dot_recorder__pb2.SendDataPointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pirateshooter.recorder.RecorderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecorderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDataPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirateshooter.recorder.RecorderService/SendDataPoint',
            recorder_dot_proto_dot_recorder__pb2.SendDataPointRequest.SerializeToString,
            recorder_dot_proto_dot_recorder__pb2.SendDataPointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
